import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { MouseEventHandler, useState } from 'react'


const Home: NextPage = () => {

  const [count, setCount] = useState(0);

  const handleOnClick:MouseEventHandler<HTMLButtonElement> = (e) => {
    setCount(count+1);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        It's Ta Quang
      </main>
    </div>
  )
}

export default Home
